### PR TITLE
About Page Implementation

### PR DESCRIPTION
**Pull request by agnlez**
- [ ] Make a class with methods for fixed menu on scroll.
- [ ] Select menu items when user scrolls (actually it only does it when users click on a link)

### CODE REVIEW

**Comment by hectoruch** [comment]
I think all is great @nerik

**Comment by nerik** [comment]
Looks good 👍  Please rebase and merge.

**Comment by nerik** [comment]
Ok I tried to rebase but I don't really know what Im doing, let @andresgnlez do it.

**Comment by agnlez** [comment]
Already merged in #78

**Pull request closed without merging**
