### PR TITLE
improve support for percentual recolor by

### PR DESCRIPTION
**Pull request by tiagojsag**
requires https://github.com/sei-international/TRASE/commit/f44cfc762d47baf9c85264d5cf28e3cea1d70eae

### CODE REVIEW

**Comment by tiagojsag** [comment]
https://basecamp.com/1756858/projects/12498794/todos/315260870

**Comment by nerik** [comment]
Seems there's a css issue:
screen shot 2017-07-18 at 12 36 24

Also, there is still a discrepancy between sankey and map tooltips (on expressed in %, one as an index), but I'm not sure it's within the scope of this PR:

screen shot 2017-07-18 at 12 37 27
screen shot 2017-07-18 at 12 37 32

**Comment by tiagojsag** [comment]
that's because of the missing changes in the db

**Comment by tiagojsag** [comment]
I updated the staging server, you should now be able to test this

**Comment by nerik** [comment]
Nice!

**Pull request merged**
