### PR TITLE
download form for data page

### PR DESCRIPTION
**Pull request by nerik**
screen shot 2017-08-23 at 13 16 14

Data is sent through a Zapier webhook (endpoint URL is in an env var) to a Google Spreadsheet named "TRASE contact form" on the account: trasecontactform@gmail.com

### CODE REVIEW

**Comment by tiagojsag** [comment]
we need a checkbox with a link to "terms foo"

**Comment by nerik** [comment]
Staging:
DATA_FORM_ENDPOINT=https://hooks.zapier.com/hooks/catch/2482873/rtdngi/

Production:
DATA_FORM_ENDPOINT=https://hooks.zapier.com/hooks/catch/2482873/r6uypm/

**Comment by nerik** [comment]
screen shot 2017-08-24 at 16 42 24

**Review by tiagojsag — CHANGES_REQUESTED** [review]
2 things:
- Can we have a feature flag to enable/disable the form?
- A target="_blank" on the "terms" link would be nice

Otherwise LGTM

**Pull request merged**
