### PR TITLE
Fix dropdown select

### PR DESCRIPTION
**Pull request by hectoruch**

### CODE REVIEW

**Comment by agnlez** [comment]
@nerik you added those styles for some reason, do you really need them? Those ones are showing selectors up badly, so we need to remove them.

**Comment by nerik** [comment]
@andresgnlez Thx for the heads up. I added this bit because the top nav dropdowns in the tool can have very long titles, messing up the whole layout.
We need to keep this, can you please move them to class and add the class to the top nav dropdowns in the tool?

**Comment by agnlez** [comment]
@hectoruch please, could you manage this? Thanks!

**Comment by hectoruch** [comment]
Yes! @andresgnlez  @nerik

**Pull request merged**
