### PR TITLE
Feature/profile header improvements

### PR DESCRIPTION
**Pull request by pjosh**
* Profile actor header with the new design
* Anchor button with the scroll behaviour
* Put the rest of the elements inside the grid (collateral damages)

captura de pantalla 2017-04-20 a las 13 38 38 2

### CODE REVIEW

**Comment by pjosh** [comment]
fixed #330 
fixed #314 
fixed #302

**Comment by nerik** [comment]
Looks good !
Two small comments:
- could we get rid of the dropdown arrows on the actor page, since they are not doing anything yet?
- there are spacing issues between the sections in the actor page
Thanks !

**Comment by pjosh** [comment]
Done @nerik !
I had not adjust the margins because we have to adjust all these modules individually, but I have already settled them more decent 😉

**Comment by nerik** [comment]
Thanks!

**Pull request merged**
