### PR TITLE
Feature/new map legend

### PR DESCRIPTION
**Pull request by pjosh**
New styles for the map legend

### CODE REVIEW

**Comment by tiagojsag** [comment]
Seems like we're missing the actual values on the the legend. Is this meant for another PR?

**Comment by pjosh** [comment]
done @tiagojsag !

**Comment by tiagojsag** [comment]
image

Seems we have inconsistent state on initial load

**Comment by tiagojsag** [comment]
also, isn't that left axis upside down?

**Comment by pjosh** [comment]
oh damn! the initial state has always works, I think that I did some mistake merging with develop... Let me check!
You're right with the axis, thanks!

**Comment by pjosh** [comment]
@tiagojsag exactly! merge mistake 😉 
Now, it should work good!

**Pull request merged**
