### PR TITLE
FAQ Page & improvements to scroll function

### PR DESCRIPTION
**Pull request by agnlez**
- Added resize event for scroll function.
- Throttle functions to not downgrade performance in slow computers.
- Added some common styles (FAQ/About pages)
- FAQ Page
- About Page (https://github.com/Vizzuality/TRASE-frontend/pull/64)

### CODE REVIEW

**Comment by hectoruch** [comment]
Change styles:
- Line-height on FAQ´s menu

Fix:
- First option on menu should be bold at the beginning.

**Comment by hectoruch** [comment]
I think all is ok @nerik

**Comment by nerik** [comment]
Looks great, please review with JC if this is the correct style for links:
screen shot 2016-10-31 at 11 41 32

Then as per @andresgnlez instruction, please merge rebase and merge #64 before this one.

**Comment by hectoruch** [comment]
Change styles for links:

image

**Comment by agnlez** [comment]
Rebased here: #78

**Pull request closed without merging**
