### PR TITLE
Multiple map colors

### PR DESCRIPTION
**Pull request by nerik**

### CODE REVIEW

**Comment by nerik** [comment]
https://github.com/Vizzuality/TRASE-frontend/issues/364

**Comment by simaob** [comment]
Hey Erik, does this solve the issue mentioned above? It seems to have a conflict at the moment.

**Comment by nerik** [comment]
This adds custom color scales for each map choropleth dimension:

screen shot 2017-05-24 at 14 22 02
screen shot 2017-05-24 at 14 22 26

@tiagojsag for now the match between dimensions and and color scales is hardcoded, as visible here:
https://github.com/Vizzuality/TRASE-frontend/pull/370/files#diff-5c68b7ce77a1b57329fcb98a0bd88134R30

Eventually, this should be set on map dimensions on the API, using a `color_scale` property, see:
https://github.com/Vizzuality/TRASE-frontend/pull/370/files#diff-16eb12a8702d04a95f97834d042b2f0dR9

This issue fixes
#364
and partially https://basecamp.com/1756858/projects/12498794/todos/308418405

**Comment by tiagojsag** [comment]
- when disabling all layers, the legend does not disappear

**Pull request merged**
