### PR TITLE
Feature/new map dimensions selector

### PR DESCRIPTION
**Pull request by nerik**

### CODE REVIEW

**Comment by nerik** [comment]
trase-dimensions

**Comment by nerik** [comment]
This :
- adds a new feature: map dimensions groups are now collapsible. This is kept in the URL state
- makes the map dimensions selection simpler, with a single radio column

Internally, in the store selected dimensions are now stored as a simple array of ids, rather than an object containing vertical/horizontal properties that don't apply anymore. Additionally CSS has been simplified and reorganized so that each component handles its own CSS (map dimensions, context and basemap)

**Comment by nerik** [comment]
https://github.com/Vizzuality/TRASE-frontend/issues/366

**Review by pjosh — COMMENTED** [review]
wow! 👏

**Pull request merged**
