### PR TITLE
Expand nodes

### PR DESCRIPTION
**Pull request by nerik**
1st objective is to be able to expand a single node (the latest selected)
This is needed for the search functionality.

We'll see later for multiple/cross column node expand

### CODE REVIEW

**Comment by nerik** [comment]
expand

**Comment by tiagojsag** [comment]
small detail: when you hover the button and it is close to the top, its top part is cut off.

**Comment by nerik** [comment]
@tiagojsag https://github.com/Vizzuality/TRASE-frontend/issues/71#issue-186238452

**Comment by nerik** [comment]
Will do a design pass when things settle down a bit

**Pull request merged**
