### PR TITLE
Display map dimension/year selection warnings when data is not available

### PR DESCRIPTION
**Pull request by nerik**
trase-warnings

Not: I haven't implemented locking dimension selection because I think it will be pretty bad for user interaction

### CODE REVIEW

**Comment by nerik** [comment]
🚨 ☢️ WARNING @tiagojsag  @tiagojsag  @tiagojsag  @tiagojsag  @tiagojsag ☢️ 🚨
Remove mock here before merging: https://github.com/Vizzuality/TRASE-frontend/pull/464/files#diff-6ff9ebf62ba84c3da2fa7618c38850bdR197
@tiagojsag

**Comment by nerik** [comment]
@tiagojsag

**Comment by tiagojsag** [comment]
@nerik review my commit and merge if ok

**Comment by nerik** [comment]
Great, thanks !

**Pull request merged**
